<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFjs9ijv\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFjs9ijv/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerFjs9ijv.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerFjs9ijv\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerFjs9ijv\appProdProjectContainer([
    'container.build_hash' => 'Fjs9ijv',
    'container.build_id' => '30a64a28',
    'container.build_time' => 1669387233,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFjs9ijv');
