<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2ndsle5\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2ndsle5/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container2ndsle5.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container2ndsle5\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container2ndsle5\appDevDebugProjectContainer([
    'container.build_hash' => '2ndsle5',
    'container.build_id' => '9843c1a5',
    'container.build_time' => 1671374285,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2ndsle5');
